### ISSUE TITLE
Support bool as an attribute type

### ISSUE THREAD

**Issue by justinchuby** [microsoft/onnx-script#283]
#281 

```python
@script()
def aten_logsumexp(self: TReal, dim: INT64["M"], keepdim: bool = False) -> TReal:
    # logsumexp(Tensor self, int[1] dim, bool keepdim=False) -> Tensor

    return op.ReduceLogSumExp(self, dim, keepdims=keepdim)
```

produces

ERROR onnxscript/test/function_libs/torch_aten/ops_correctness_test.py - TypeError: value "<onnxscript.values.Dynamic object at 0x7f2611f68640>" is not valid attribute data type.

Even though `dim` should be an input?

cc @gramalingam @fatcat-z @xiaowuhu

**Comment by gramalingam** [comment]
Quick question: is this with the latest opset of ONNX, which updates ReduceLogSumExp?

**Comment by justinchuby** [comment]
I was using opset18. onnxruntime 1.13 I think

**Comment by gramalingam** [comment]
Ok, the problem is with keepdim. Currently, onnxscript doesn't recognize the "bool" type as a valid attribute type. (ONNX doesn't have bool attributes, it uses int attributes even for booleans.) So, if I use `int` it seems to work for now. We could extend the translator to support bool attributes and map them automatically to int attributes.

**Comment by justinchuby** [comment]
I see! That makes a lot of sense. I like the idea of supporting bool since it is a kind of int even in Python
